### ISSUE TITLE
An English version?

### ISSUE THREAD

**Issue by olufemioyedepo** [soybeanjs/soybean-admin#20]
Hi guys,
Great job so far on this template but can we get an english version @lingdu1234 @yanbowe ?

**Comment by honghuangdc** [comment]
Hi, brother. first all of, I'm appreciated that you can have a deep impression on this project. It's a hard work to make an english version because almost all work was did by me on this project in my spare time. Maybe after the project is ready to publish the official version 1.0, I will set about doing the translate work.

**Comment by olufemioyedepo** [comment]
OK that's well understood

**Comment by acidbotmaker** [comment]
@honghuangdc any update?
I'm happy to help for the english version if that's an option.

I really like this project and want to try it out

**Comment by honghuangdc** [comment]
> @honghuangdc any update? I'm happy to help for the english version if that's an option.
> 
> I really like this project and want to try it out

of course!
I'm recently preparing to write the documentation for the new version of v1.0, when I'm done with the Chinese version, can you help me write an English version, thanks!

**Comment by honghuangdc** [comment]
- [ ] English README.md
- [ ] document
